### PR TITLE
Update config.go

### PR DESCRIPTION
**Pull request by chuhlomin**
Note about `EnvAppName`

### CODE REVIEW

**Comment by jprobinson** [comment]
I have never run into the need of including a "_" prefix for environment variables? When have you run into this?

**Comment by jprobinson** [comment]
You can give this example a try if you want to double check: https://github.com/NYTimes/gizmo/tree/master/examples/servers/simple

Do a `source .env` before running the server and everything should work fine.

**Comment by chuhlomin** [comment]
Coming from this line: https://github.com/kelseyhightower/envconfig/blob/master/envconfig.go#L70
I tried to run Gizmo with variable like `RPC_PORT` and found that it dosn't see it unless there is a "_" prefix. 
Alright, let me try an example.

**Comment by chuhlomin** [comment]
You right, example works locally. And envcofing does 2 Getenv calls, first with prefix, second – without it (https://github.com/kelseyhightower/envconfig/blob/master/envconfig.go#L76).
Nevermind this pull request then.

**Pull request closed without merging**
